"""pay-log

Revision ID: 573b66bd5e40
Revises: 1c1d20c63a69
Create Date: 2025-03-14 21:17:34.605981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573b66bd5e40'
down_revision: Union[str, None] = '1c1d20c63a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('author_email', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['author_email'], ['user.email'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('payment_debt_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'debt', ['debt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_debt_id_fkey', 'payment', 'debt', ['debt_id'], ['id'])
    op.drop_table('pay_log')
    # ### end Alembic commands ###
